export const empleadosData = [
    {
        "clave": "2125",
        "nombre": "HERNANDEZ MARIN JOSE RAMIRO             ",
        "plaza": "DIRECTOR DE AREA                   ",
        "direccion": "PRIVADA PLASCENCIA 13                                                 ",
        "colNomb": "VILLA BONITA                       ",
        "ciuNomb": "HERMOSILLO, SONORA                 ",
        "telefono": "               ",
        "telefami": "               ",
        "celular": "6621805180     ",
        "lugNac": "HERMOSILLO, SONORA                 ",
        "fecNac": "1961-10-31T00:00:00",
        "sexo": 2,
        "escolaridad": "PROFESIONISTA (TITULADO)           ",
        "edoCiv": "CASADO (A)                         ",
        "conyuge": "ANDALON MARTINEZ LILIANA           ",
        "fecNacCon": "09/18/1967 00:00:00",
        "fecMatr": "    ",
        "fecha_ingreso": "2021-12-08T00:00:00",
        "fecha_baja": "0001-01-01T00:00:00",
        "funciones": "SUBDIRECTOR DE SEGUIMIENTO A PROGRAMAS ALIMENTARIOS         ",
        "nivel": "11 ",
        "nivel_homo": "   ",
        "adscripcion": "DIR. PROG. ALIM. Y DES. COM.       ",
        "tpoNom": "NOMINA INTERNA                     ",
        "condLabo": "CONFIANZA                          ",
        "entrada_1": "08:00",
        "salida_1": "15:00",
        "entrada_2": "     ",
        "salida_2": "     ",
        "trabaja_lun": 1,
        "trabaja_mar": 1,
        "trabaja_mie": 1,
        "trabaja_jue": 1,
        "trabaja_vie": 1,
        "trabaja_sab": 0,
        "trabaja_dom": 0,
        "checa": 1,
        "dias_festivos": 0,
        "p_sindicato": 0,
        "sueldo": 0,
        "compensacion": 0,
        "prestac_ley": 0,
        "prestaciones": 0,
        "deducciones": 0,
        "sueldo2": 0,
        "compensacion2": 0,
        "prestac_ley2": 0,
        "prestaciones2": 0,
        "deducciones2": 0,
        "fecha_base": "0001-01-01T00:00:00",
        "cmpimp20": 0,
        "cmpimpsifem": 0,
        "cmpprocom": 0,
        "email": "jrhernandezmarin@gmail.com                        "
    },
    {
        "clave": "9447",
        "nombre": "VIDAÑA GARCIA JULIO CESAR               ",
        "plaza": "DIRECTOR DE AREA                   ",
        "direccion": "CIRCUITO DEL ROBLE NO.125                                             ",
        "colNomb": "DEL BOSQUE                         ",
        "ciuNomb": "HERMOSILLO, SONORA                 ",
        "telefono": "               ",
        "telefami": "               ",
        "celular": "6622 292415    ",
        "lugNac": "EMPALME, SONORA                    ",
        "fecNac": "1987-08-20T00:00:00",
        "sexo": 2,
        "escolaridad": "BACHILLERATO                       ",
        "edoCiv": "CASADO (A)                         ",
        "conyuge": "PAZOS TRUJILLO ANALI               ",
        "fecNacCon": "04/16/1990 00:00:00",
        "fecMatr": "2009",
        "fecha_ingreso": "2015-09-25T00:00:00",
        "fecha_baja": "0001-01-01T00:00:00",
        "funciones": "SUBD. DE SISTEMAS Y TECNOLOGIAS                             ",
        "nivel": "11 ",
        "nivel_homo": "   ",
        "adscripcion": "DIRECCION DE PLANEACION Y FINANZAS ",
        "tpoNom": "NOMINA INTERNA                     ",
        "condLabo": "CONFIANZA                          ",
        "entrada_1": "08:00",
        "salida_1": "16:00",
        "entrada_2": "     ",
        "salida_2": "     ",
        "trabaja_lun": 1,
        "trabaja_mar": 1,
        "trabaja_mie": 1,
        "trabaja_jue": 1,
        "trabaja_vie": 1,
        "trabaja_sab": 0,
        "trabaja_dom": 0,
        "checa": 1,
        "dias_festivos": 0,
        "p_sindicato": 0,
        "sueldo": 26664.74,
        "compensacion": 5000,
        "prestac_ley": 0,
        "prestaciones": 0,
        "deducciones": 9383.78,
        "sueldo2": 26664.74,
        "compensacion2": 5000,
        "prestac_ley2": 0,
        "prestaciones2": 0,
        "deducciones2": 9383.78,
        "fecha_base": "0001-01-01T00:00:00",
        "cmpimp20": 0,
        "cmpimpsifem": 0,
        "cmpprocom": 0,
        "email": "julio.vidana@difson.gob.mx                        "
    },
    {
        "clave": "9442",
        "nombre": "BORQUEZ ESPINOZA SUGEHIRA               ",
        "plaza": "SUBDIRECTOR GENERAL                ",
        "direccion": "CALLE RIO FUERTE NO. 134                                              ",
        "colNomb": "NACAMERI                           ",
        "ciuNomb": "HERMOSILLO, SONORA                 ",
        "telefono": "               ",
        "telefami": "               ",
        "celular": "6622 225893    ",
        "lugNac": "MAZATAN, SONORA                    ",
        "fecNac": "1976-08-09T00:00:00",
        "sexo": 1,
        "escolaridad": "PROFESIONISTA (C. INCONCLUSA)      ",
        "edoCiv": "CASADO (A)                         ",
        "conyuge": "VERDUGO ESTRADA CARLOS ALBERTO     ",
        "fecNacCon": "01/27/1977 00:00:00",
        "fecMatr": "    ",
        "fecha_ingreso": "2015-09-23T00:00:00",
        "fecha_baja": "0001-01-01T00:00:00",
        "funciones": "COORD. DE CONTROL ADMINISTRATIVO Y SEG.ASUNTOS JURIDICOS    ",
        "nivel": "10 ",
        "nivel_homo": "   ",
        "adscripcion": "UNIDAD DE ASESORIA LEGAL           ",
        "tpoNom": "NOMINA INTERNA                     ",
        "condLabo": "CONFIANZA                          ",
        "entrada_1": "08:00",
        "salida_1": "16:00",
        "entrada_2": "     ",
        "salida_2": "     ",
        "trabaja_lun": 1,
        "trabaja_mar": 1,
        "trabaja_mie": 1,
        "trabaja_jue": 1,
        "trabaja_vie": 1,
        "trabaja_sab": 0,
        "trabaja_dom": 0,
        "checa": 1,
        "dias_festivos": 0,
        "p_sindicato": 0,
        "sueldo": 19334.8,
        "compensacion": 3000,
        "prestac_ley": 0,
        "prestaciones": 0,
        "deducciones": 5419.42,
        "sueldo2": 19334.8,
        "compensacion2": 3000,
        "prestac_ley2": 0,
        "prestaciones2": 0,
        "deducciones2": 5419.42,
        "fecha_base": "0001-01-01T00:00:00",
        "cmpimp20": 0,
        "cmpimpsifem": 0,
        "cmpprocom": 0,
        "email": "sugehira.borquez@difson.gob.mx                    "
    },
    {
        "clave": "9426",
        "nombre": "APODACA IBARRA ROXANA MARIA             ",
        "plaza": "SUBDIRECTOR GENERAL                ",
        "direccion": "RETORNO DOGLIANI 57                                                   ",
        "colNomb": "VILLA RESIDENCIAL BONITA           ",
        "ciuNomb": "HERMOSILLO, SONORA                 ",
        "telefono": "               ",
        "telefami": "               ",
        "celular": "6621570707     ",
        "lugNac": "MAGDALENA, SONORA                  ",
        "fecNac": "1972-03-02T00:00:00",
        "sexo": 1,
        "escolaridad": "MAESTRÍA                           ",
        "edoCiv": "SOLTERO (A)                        ",
        "conyuge": "                                   ",
        "fecNacCon": null,
        "fecMatr": "    ",
        "fecha_ingreso": "2015-09-22T00:00:00",
        "fecha_baja": "0001-01-01T00:00:00",
        "funciones": "SUBDIRECTORA DE LICITACIONES                                ",
        "nivel": "10 ",
        "nivel_homo": "   ",
        "adscripcion": "DIR. DE RECURSOS MAT Y SERV. GRALES",
        "tpoNom": "NOMINA INTERNA                     ",
        "condLabo": "CONFIANZA                          ",
        "entrada_1": "08:00",
        "salida_1": "16:00",
        "entrada_2": "     ",
        "salida_2": "     ",
        "trabaja_lun": 1,
        "trabaja_mar": 1,
        "trabaja_mie": 1,
        "trabaja_jue": 1,
        "trabaja_vie": 1,
        "trabaja_sab": 0,
        "trabaja_dom": 0,
        "checa": 1,
        "dias_festivos": 0,
        "p_sindicato": 0,
        "sueldo": 19334.8,
        "compensacion": 0,
        "prestac_ley": 0,
        "prestaciones": 0,
        "deducciones": 4320.12,
        "sueldo2": 19334.8,
        "compensacion2": 0,
        "prestac_ley2": 0,
        "prestaciones2": 0,
        "deducciones2": 4320.12,
        "fecha_base": "0001-01-01T00:00:00",
        "cmpimp20": 0,
        "cmpimpsifem": 0,
        "cmpprocom": 0,
        "email": "roxana.apodaca@difson.gob.mx                      "
    },
    {
        "clave": "1223",
        "nombre": "BORQUEZ GUERRERO TANHYA KARINA          ",
        "plaza": "DIRECTOR DE AREA                   ",
        "direccion": "ENRIQUE B. MICHEL # 93 / FIDEL VELASQUEZ Y EMILIANA DE ZUBELDIA       ",
        "colNomb": "REVOLUCION I                       ",
        "ciuNomb": "HERMOSILLO, SONORA                 ",
        "telefono": "217 51 92      ",
        "telefami": "               ",
        "celular": "6621680819     ",
        "lugNac": "HERMOSILLO, SONORA                 ",
        "fecNac": "1984-09-06T00:00:00",
        "sexo": 1,
        "escolaridad": "PROFESIONISTA (TITULADO)           ",
        "edoCiv": "CASADO (A)                         ",
        "conyuge": "CHRISTIAN VASQUEZ MONTAÑO          ",
        "fecNacCon": null,
        "fecMatr": "1710",
        "fecha_ingreso": "2015-09-21T00:00:00",
        "fecha_baja": "0001-01-01T00:00:00",
        "funciones": "SUBDIRECTORA DE PROTECION A LA NIÑEZ                        ",
        "nivel": "11 ",
        "nivel_homo": "   ",
        "adscripcion": "PROC DE PROT DE NIÑAS NIÑOS Y ADOL ",
        "tpoNom": "NOMINA INTERNA                     ",
        "condLabo": "CONFIANZA                          ",
        "entrada_1": "08:00",
        "salida_1": "15:00",
        "entrada_2": "  :  ",
        "salida_2": "  :  ",
        "trabaja_lun": 1,
        "trabaja_mar": 1,
        "trabaja_mie": 1,
        "trabaja_jue": 1,
        "trabaja_vie": 1,
        "trabaja_sab": 0,
        "trabaja_dom": 0,
        "checa": 1,
        "dias_festivos": 0,
        "p_sindicato": 0,
        "sueldo": 26664.74,
        "compensacion": 5000,
        "prestac_ley": 0,
        "prestaciones": 0,
        "deducciones": 9383.78,
        "sueldo2": 26664.74,
        "compensacion2": 5000,
        "prestac_ley2": 0,
        "prestaciones2": 0,
        "deducciones2": 9383.78,
        "fecha_base": "0001-01-01T00:00:00",
        "cmpimp20": 0,
        "cmpimpsifem": 0,
        "cmpprocom": 0,
        "email": "tanhya.borquez@difson.gob.mx                      "
    },
    {
        "clave": "9431",
        "nombre": "MARTINEZ HERNANDEZ MARIA EUGENIA        ",
        "plaza": "JEFE DE DEPARTAMENTO               ",
        "direccion": "CALLE MARIANO JIMENEZ NO. 882                                         ",
        "colNomb": "NUEVA CASTILLA                     ",
        "ciuNomb": "HERMOSILLO, SONORA                 ",
        "telefono": "2602320        ",
        "telefami": "               ",
        "celular": "6622 57 31 89  ",
        "lugNac": "HERMOSILLO, SONORA                 ",
        "fecNac": "1990-05-15T00:00:00",
        "sexo": 1,
        "escolaridad": "PROFESIONISTA (TITULADO)           ",
        "edoCiv": "SOLTERO (A)                        ",
        "conyuge": "                                   ",
        "fecNacCon": null,
        "fecMatr": "    ",
        "fecha_ingreso": "2015-09-18T00:00:00",
        "fecha_baja": "0001-01-01T00:00:00",
        "funciones": "ENC.FOTOGRAFIA,EDICION,VIDEO Y APOYO DE ASESORIA E IMAGEN   ",
        "nivel": "09 ",
        "nivel_homo": "   ",
        "adscripcion": "UNIDAD DE COMUNICACION SOCIAL      ",
        "tpoNom": "NOMINA INTERNA                     ",
        "condLabo": "CONFIANZA                          ",
        "entrada_1": "08:00",
        "salida_1": "16:00",
        "entrada_2": "     ",
        "salida_2": "     ",
        "trabaja_lun": 1,
        "trabaja_mar": 1,
        "trabaja_mie": 1,
        "trabaja_jue": 1,
        "trabaja_vie": 1,
        "trabaja_sab": 0,
        "trabaja_dom": 0,
        "checa": 1,
        "dias_festivos": 0,
        "p_sindicato": 0,
        "sueldo": 18587.48,
        "compensacion": 5000,
        "prestac_ley": 0,
        "prestaciones": 0,
        "deducciones": 5877.48,
        "sueldo2": 18587.48,
        "compensacion2": 5000,
        "prestac_ley2": 0,
        "prestaciones2": 0,
        "deducciones2": 5877.48,
        "fecha_base": "0001-01-01T00:00:00",
        "cmpimp20": 0,
        "cmpimpsifem": 0,
        "cmpprocom": 0,
        "email": "maria.martinez@difson.gob.mx                      "
    },
    {
        "clave": "1727",
        "nombre": "YAÑEZ ENRIQUEZ LUIS ENRIQUE             ",
        "plaza": "COORDINADOR ADMINISTRATIVO         ",
        "direccion": "CASTELLANA NO.46 ESQ. CON MURCIA                                      ",
        "colNomb": "LAS GRANJAS                        ",
        "ciuNomb": "HERMOSILLO, SONORA                 ",
        "telefono": "2130433        ",
        "telefami": "               ",
        "celular": "6621607417     ",
        "lugNac": "HERMOSILLO, SONORA                 ",
        "fecNac": "1977-11-09T00:00:00",
        "sexo": 2,
        "escolaridad": "SECUNDARIA TERMINADA               ",
        "edoCiv": "SOLTERO (A)                        ",
        "conyuge": "                                   ",
        "fecNacCon": null,
        "fecMatr": "    ",
        "fecha_ingreso": "2015-08-01T00:00:00",
        "fecha_baja": "0001-01-01T00:00:00",
        "funciones": "AUXILIAR MANTENIMIENTO                                      ",
        "nivel": "02B",
        "nivel_homo": "   ",
        "adscripcion": "HOGAR TEMP P/NNA SIT CALLE JINESEKI",
        "tpoNom": "NOMINA INTERNA                     ",
        "condLabo": "CONFIANZA                          ",
        "entrada_1": "08:00",
        "salida_1": "15:00",
        "entrada_2": "     ",
        "salida_2": "     ",
        "trabaja_lun": 1,
        "trabaja_mar": 1,
        "trabaja_mie": 1,
        "trabaja_jue": 1,
        "trabaja_vie": 1,
        "trabaja_sab": 0,
        "trabaja_dom": 0,
        "checa": 1,
        "dias_festivos": 0,
        "p_sindicato": 0,
        "sueldo": 8851.08,
        "compensacion": 0,
        "prestac_ley": 0,
        "prestaciones": 0,
        "deducciones": 1777.76,
        "sueldo2": 8851.08,
        "compensacion2": 0,
        "prestac_ley2": 0,
        "prestaciones2": 0,
        "deducciones2": 1777.76,
        "fecha_base": "0001-01-01T00:00:00",
        "cmpimp20": 0,
        "cmpimpsifem": 0,
        "cmpprocom": 0,
        "email": "Luisenriqueyanezenriquez70@gmail.com              "
    },
    {
        "clave": "9381",
        "nombre": "RUIZ CARRILLO ROSA                      ",
        "plaza": "COORDINADOR ADMINISTRATIVO         ",
        "direccion": "AVE. LEOPOLDO RAMOS # 591                                             ",
        "colNomb": "CHOYAL                             ",
        "ciuNomb": "HERMOSILLO, SONORA                 ",
        "telefono": "               ",
        "telefami": "               ",
        "celular": "6621261948     ",
        "lugNac": "HERMOSILLO, SONORA                 ",
        "fecNac": "1959-10-09T00:00:00",
        "sexo": 1,
        "escolaridad": "SECUNDARIA TERMINADA               ",
        "edoCiv": "SOLTERO (A)                        ",
        "conyuge": "                                   ",
        "fecNacCon": null,
        "fecMatr": "    ",
        "fecha_ingreso": "2015-06-01T00:00:00",
        "fecha_baja": "0001-01-01T00:00:00",
        "funciones": "ASISTENTE EDUCATIVA                                         ",
        "nivel": "02B",
        "nivel_homo": "   ",
        "adscripcion": "CENTRO ASISTENCIA SOCIAL UNACARI   ",
        "tpoNom": "NOMINA INTERNA                     ",
        "condLabo": "CONFIANZA                          ",
        "entrada_1": "12:30",
        "salida_1": "19:30",
        "entrada_2": "     ",
        "salida_2": "     ",
        "trabaja_lun": 1,
        "trabaja_mar": 1,
        "trabaja_mie": 1,
        "trabaja_jue": 1,
        "trabaja_vie": 1,
        "trabaja_sab": 0,
        "trabaja_dom": 0,
        "checa": 1,
        "dias_festivos": 0,
        "p_sindicato": 0,
        "sueldo": 8851.08,
        "compensacion": 500,
        "prestac_ley": 0,
        "prestaciones": 0,
        "deducciones": 2016.78,
        "sueldo2": 8851.08,
        "compensacion2": 500,
        "prestac_ley2": 0,
        "prestaciones2": 0,
        "deducciones2": 2016.78,
        "fecha_base": "0001-01-01T00:00:00",
        "cmpimp20": 0,
        "cmpimpsifem": 0,
        "cmpprocom": 0,
        "email": "Rossyruiz0910@gmail.com                           "
    },
    {
        "clave": "5501",
        "nombre": "MONTAÑO MOJUTA SILVIA LIZETH            ",
        "plaza": "PROFESIONISTA ESPECIALIZADO        ",
        "direccion": "HERIBERTO AJA # 42 / TAMAULIPAS Y ZACATECAS                           ",
        "colNomb": "COL. CENTRO                        ",
        "ciuNomb": "HERMOSILLO, SONORA                 ",
        "telefono": "3014825        ",
        "telefami": "               ",
        "celular": "6622240315     ",
        "lugNac": "HERMOSILLO, SONORA                 ",
        "fecNac": "1978-11-03T00:00:00",
        "sexo": 1,
        "escolaridad": "PROFESIONISTA (TITULADO)           ",
        "edoCiv": "SOLTERO (A)                        ",
        "conyuge": "                                   ",
        "fecNacCon": null,
        "fecMatr": "    ",
        "fecha_ingreso": "2015-04-16T00:00:00",
        "fecha_baja": "0001-01-01T00:00:00",
        "funciones": "CREADOR DE CONT.DE MEDIOS DIGITALES                         ",
        "nivel": "08B",
        "nivel_homo": "   ",
        "adscripcion": "UNIDAD DE COMUNICACION SOCIAL      ",
        "tpoNom": "NOMINA INTERNA                     ",
        "condLabo": "BASE                               ",
        "entrada_1": "08:00",
        "salida_1": "15:00",
        "entrada_2": "  :  ",
        "salida_2": "  :  ",
        "trabaja_lun": 1,
        "trabaja_mar": 1,
        "trabaja_mie": 1,
        "trabaja_jue": 1,
        "trabaja_vie": 1,
        "trabaja_sab": 0,
        "trabaja_dom": 0,
        "checa": 1,
        "dias_festivos": 0,
        "p_sindicato": 1,
        "sueldo": 18199.42,
        "compensacion": 0,
        "prestac_ley": 5350.94,
        "prestaciones": 0,
        "deducciones": 8468.24,
        "sueldo2": 18199.42,
        "compensacion2": 0,
        "prestac_ley2": 5350.94,
        "prestaciones2": 0,
        "deducciones2": 8468.24,
        "fecha_base": "0001-01-01T00:00:00",
        "cmpimp20": 0,
        "cmpimpsifem": 0,
        "cmpprocom": 0,
        "email": "silvia.montano@difson.gob.mx                      "
    },
    {
        "clave": "9367",
        "nombre": "GALVEZ PAZ KARLA PATRICIA               ",
        "plaza": "ANALISTA TECNICO                   ",
        "direccion": "CALLE LOS POCITOS NO. 48                                              ",
        "colNomb": "SANTA FE                           ",
        "ciuNomb": "HERMOSILLO, SONORA                 ",
        "telefono": "               ",
        "telefami": "               ",
        "celular": "6624753127     ",
        "lugNac": "HERMOSILLO, SONORA                 ",
        "fecNac": "1984-05-12T00:00:00",
        "sexo": 1,
        "escolaridad": "PROFESIONISTA (TITULADO)           ",
        "edoCiv": "CASADO (A)                         ",
        "conyuge": "HECTOR ARMANDO CARRANZA ROBLES     ",
        "fecNacCon": null,
        "fecMatr": "    ",
        "fecha_ingreso": "2015-04-01T00:00:00",
        "fecha_baja": "0001-01-01T00:00:00",
        "funciones": "COORDINADORA DE ASISTENCIA ALIMENTARIA                      ",
        "nivel": "05I",
        "nivel_homo": "   ",
        "adscripcion": "DIR. PROG. ALIM. Y DES. COM.       ",
        "tpoNom": "NOMINA INTERNA                     ",
        "condLabo": "CONFIANZA                          ",
        "entrada_1": "08:00",
        "salida_1": "15:00",
        "entrada_2": "     ",
        "salida_2": "     ",
        "trabaja_lun": 1,
        "trabaja_mar": 1,
        "trabaja_mie": 1,
        "trabaja_jue": 1,
        "trabaja_vie": 1,
        "trabaja_sab": 0,
        "trabaja_dom": 0,
        "checa": 1,
        "dias_festivos": 0,
        "p_sindicato": 0,
        "sueldo": 12312.06,
        "compensacion": 0,
        "prestac_ley": 0,
        "prestaciones": 0,
        "deducciones": 2475.58,
        "sueldo2": 12312.06,
        "compensacion2": 0,
        "prestac_ley2": 0,
        "prestaciones2": 0,
        "deducciones2": 2475.58,
        "fecha_base": "0001-01-01T00:00:00",
        "cmpimp20": 0,
        "cmpimpsifem": 0,
        "cmpprocom": 0,
        "email": "karla.galvez@difson.gob.mx                        "
    },
    {
        "clave": "9327",
        "nombre": "SOUFFLE OLAJE JESUS EDGARDO             ",
        "plaza": "JEFE DE AREA                       ",
        "direccion": "AVE. EDUARDO W. VILLA # 135                                           ",
        "colNomb": "JESUS GARCIA                       ",
        "ciuNomb": "HERMOSILLO, SONORA                 ",
        "telefono": "               ",
        "telefami": "210 95 76      ",
        "celular": "66 22 261654   ",
        "lugNac": "HERMOSILLO, SONORA                 ",
        "fecNac": "1987-12-25T00:00:00",
        "sexo": 2,
        "escolaridad": "PRIMARIA TERMINADA                 ",
        "edoCiv": "SOLTERO (A)                        ",
        "conyuge": "                                   ",
        "fecNacCon": null,
        "fecMatr": "    ",
        "fecha_ingreso": "2015-02-16T00:00:00",
        "fecha_baja": "0001-01-01T00:00:00",
        "funciones": "RECEPCIONISTA DE OFICINAS GENERALES                         ",
        "nivel": "03I",
        "nivel_homo": "   ",
        "adscripcion": "DIRECCION GENERAL                  ",
        "tpoNom": "NOMINA INTERNA                     ",
        "condLabo": "BASE                               ",
        "entrada_1": "08:00",
        "salida_1": "15:00",
        "entrada_2": "     ",
        "salida_2": "     ",
        "trabaja_lun": 1,
        "trabaja_mar": 1,
        "trabaja_mie": 1,
        "trabaja_jue": 1,
        "trabaja_vie": 1,
        "trabaja_sab": 0,
        "trabaja_dom": 0,
        "checa": 1,
        "dias_festivos": 0,
        "p_sindicato": 1,
        "sueldo": 8851.08,
        "compensacion": 500,
        "prestac_ley": 0,
        "prestaciones": 0,
        "deducciones": 2016.78,
        "sueldo2": 8851.08,
        "compensacion2": 500,
        "prestac_ley2": 0,
        "prestaciones2": 0,
        "deducciones2": 2016.78,
        "fecha_base": "2020-12-16T00:00:00",
        "cmpimp20": 0,
        "cmpimpsifem": 0,
        "cmpprocom": 0,
        "email": "jesus.soufle@difson.gob.mx                        "
    },
    {
        "clave": "1711",
        "nombre": "ROBLES SOTO ALVARO ENRIQUE              ",
        "plaza": "COORDINADOR TECNICO                ",
        "direccion": "CIRCUITO DEL PIÑEIRO NO. 34                                           ",
        "colNomb": "LOS GIRASOLES                      ",
        "ciuNomb": "HERMOSILLO, SONORA                 ",
        "telefono": "               ",
        "telefami": "               ",
        "celular": "6623 95 17 52  ",
        "lugNac": "AHOME, SINALOA                     ",
        "fecNac": "1973-02-19T00:00:00",
        "sexo": 2,
        "escolaridad": "PROFESIONISTA (TITULADO)           ",
        "edoCiv": "CASADO (A)                         ",
        "conyuge": "MARIBEL ARAUJO GOMEZ               ",
        "fecNacCon": "08/06/1988 00:00:00",
        "fecMatr": "0810",
        "fecha_ingreso": "2015-01-16T00:00:00",
        "fecha_baja": "0001-01-01T00:00:00",
        "funciones": "MEDICO ESPECIALISTA EN OFTALMOLOGIA                         ",
        "nivel": "06A",
        "nivel_homo": "   ",
        "adscripcion": "CENTRO DE REHAB. Y EDUC. ESPECIAL  ",
        "tpoNom": "NOMINA INTERNA                     ",
        "condLabo": "CONFIANZA                          ",
        "entrada_1": "09:00",
        "salida_1": "13:00",
        "entrada_2": "     ",
        "salida_2": "     ",
        "trabaja_lun": 1,
        "trabaja_mar": 1,
        "trabaja_mie": 1,
        "trabaja_jue": 1,
        "trabaja_vie": 1,
        "trabaja_sab": 0,
        "trabaja_dom": 0,
        "checa": 1,
        "dias_festivos": 0,
        "p_sindicato": 0,
        "sueldo": 15001.54,
        "compensacion": 0,
        "prestac_ley": 0,
        "prestaciones": 0,
        "deducciones": 2890.14,
        "sueldo2": 15001.54,
        "compensacion2": 0,
        "prestac_ley2": 0,
        "prestaciones2": 0,
        "deducciones2": 2890.14,
        "fecha_base": "0001-01-01T00:00:00",
        "cmpimp20": 0,
        "cmpimpsifem": 0,
        "cmpprocom": 0,
        "email": "dr.robles73@hotmail.com                           "
    },
]